
class Config:

    API_RATE_LIMIT = 10

    API_REQUEST_INTERVAL = 0.5

    CAT_FACT_WORD_META = {"table_name": "CAT_FACT_WORD_COUNT",
                          "entity_name": "WORD", "entity_count": "WORD_COUNT"}
    CAT_FACT_UNICODE_META = {"table_name": "CAT_FACT_UNICODE_COUNT",
                             "entity_name": "UNICODE", "entity_count": "UNICODE_COUNT"}
    CAT_FACT_DDL = """
	CREATE TABLE IF NOT EXISTS CAT_FACTS(
  	FACT_PK_KEY    TEXT PRIMARY KEY NOT NULL,
	FACT           TEXT NOT NULL
	"""

    CAT_FACT_WORDS_DDL = f"""
	CREATE TABLE IF NOT EXISTS {CAT_FACT_WORD_META["table_name"]}(
  	FACT_FK_KEY    TEXT NOT NULL,
	{CAT_FACT_WORD_META["entity_name"]} TEXT NOT NULL,
	{CAT_FACT_WORD_META["entity_count"]} INTEGER NOT NULL
	FOREIGN KEY (FACT_FK_KEY) REFERENCES CAT_FACTS(FACT_PK_KEY)
	"""

    CAT_FACT_UNICODE_DDL = f"""
	CREATE TABLE IF NOT EXISTS {CAT_FACT_UNICODE_META["table_name"]}(
  	FACT_FK_KEY    TEXT NOT NULL,
	{CAT_FACT_UNICODE_META["entity_name"]} TEXT NOT NULL,
	{CAT_FACT_UNICODE_META["entity_count"]} INTEGER NOT NULL
	FOREIGN KEY (FACT_FK_KEY) REFERENCES CAT_FACTS(FACT_PK_KEY)
	"""
