
class Config:

    API_RATE_LIMIT = 10

    API_REQUEST_INTERVAL = 0.1

    COUNTRY_DDL = """
   	CREATE TABLE IF NOT EXISTS COUNTRIES(
  	COUNTRY_NAME   TEXT PRIMARY KEY NOT NULL,
	NATIONALITY    TEXT NOT NULL 
	)
    """

    CAT_FACT_DDL = """
	CREATE TABLE IF NOT EXISTS CAT_FACTS(
  	FACT_PK_KEY    TEXT PRIMARY KEY NOT NULL,
	FACT           TEXT NOT NULL
	)
	"""

    CAT_FACT_WORDS_DDL = """
	CREATE TABLE IF NOT EXISTS CAT_FACT_WORD_COUNT(
  	FACT_FK_KEY    TEXT NOT NULL,
	WORD       TEXT NOT NULL,
	WORD_COUNT INTEGER NOT NULL,
	FOREIGN KEY (FACT_FK_KEY) REFERENCES CAT_FACTS(FACT_PK_KEY)
	)
	"""

    CAT_FACT_UNICODE_DDL = """
	CREATE TABLE IF NOT EXISTS CAT_FACT_UNICODE_COUNT(
  	FACT_FK_KEY    TEXT NOT NULL,
	UNICODE TEXT NOT NULL,
	UNICODE_COUNT INTEGER NOT NULL,
	FOREIGN KEY (FACT_FK_KEY) REFERENCES CAT_FACTS(FACT_PK_KEY)
	)
	"""
